{{- if not .Values.existingSecret.name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bitbucket-rqlite-cache.fullname" . }}
  labels:
    {{- include "bitbucket-rqlite-cache.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | toString | quote }}
  {{- end }}
{{- end }}
