replicaCount: 1

image:
  repository: ghcr.io/zystem/bitbucket-rqlite-cache
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  capabilities:
    drop:
      - ALL

existingSecret:
  name: ""
# OR
env:
  BITBUCKET_WORKSPACE: ""
  BITBUCKET_REPO_PATTERNS: ""
  BITBUCKET_API_URL: "https://api.bitbucket.org/2.0/repositories"
  BITBUCKET_USER: ""
  BITBUCKET_TOKEN: ""
  RQLITE_URL: ""
  RQLITE_USER: ""
  RQLITE_PASSWORD: ""
  SYNC_SLEEP_SECONDS: "1"
  BITBUCKET_RATE_LIMIT_SLEEP_SECONDS: "60"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe: {}
readinessProbe: {}

nodeSelector: {}
tolerations: []
affinity: {}
